### ISSUE TITLE
[Tracker] Explore using k8s static pod or crictl for creating dnsmasq container

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#696]
Recently we hit 2 bugs for podman https://bugzilla.redhat.com/show_bug.cgi?id=1758500 [_Restarting the crio service remove config.json for podman containers_] and https://bugzilla.redhat.com/show_bug.cgi?id=1729603 [_port forwarding to containers run via podman does not appear to work_] which keep us thinking to find an alternative to run the `dnsmasq` container before starting the cluster. 

Current options are either using k8s static pods ( https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/ ) or directly using crictl ( https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md ).

k8s static pods not going to works for us since it start with kubelet service and till that time we are late to add the nameserver details to `/etc/resolv.conf`.

```
apiVersion: v1
kind: Pod
metadata:
  name: dnsmasq
  labels:
    k8s-app: dnsmasq
spec:
  containers:
  - name: dnsmasq
    image: "quay.io/crcont/dnsmasq:latest"
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - name: dnsmasq-config
      mountPath: /etc/dnsmasq.conf
    ports:
    - name: dnsmasq
      containerPort: 53
      protocol: UDP
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: "Exists"
  restartPolicy: Always
  volumes:
  - name: dnsmasq-config
    hostPath:
      path: /var/srv/dnsmasq.conf
```

crictl communicate with CRI specification which crio provides and mostly used for debugging purpose of k8s side https://blog.openshift.com/crictl-vs-podman/ contains some of the points. 

Also crictl doesn't have flexibility to create the container and mostly use just to test container runtime https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/#create-a-container
```
# crictl create -h
NAME:
   crictl create - Create a new container

USAGE:
   crictl create POD container-config.[json|yaml] pod-config.[json|yaml]
```

So our only option still be podman, we need to make sure it doesn't break and test it proactively.
