### ISSUE TITLE
Use Travis test matrix for multiple GO versions

### ISSUE THREAD

**Issue by ArangoGutierrez** [code-ready/crc#704]
Travis has a way to matrix test the version of a language dependency

-> https://docs.travis-ci.com/user/languages/go/#specifying-a-go-version-to-use

```yaml
language: go

go:
- 1.11.x
- 1.12.x
- 1.13.x
```

This will help moving forward on testing if new versions of GO break crc build or any specific features
